extends RefCounted
class_name MigrationLocalization

static var language := "zh"

const EN := {
	"第一章 · 绿洲边缘": "Chapter 1 · Oasis Edge",
	"第二章 · 明亮沙丘": "Chapter 2 · Bright Dunes",
	"第一章": "Chapter 1",
	"第二章": "Chapter 2",
	"第 1 关 · 初次开路": "Level 1 · First Path",
	"第 2 关 · 道路相邻": "Level 2 · Connected Roads",
	"第 3 关 · 绕过岩石": "Level 3 · Around the Rocks",
	"第 4 关 · 拖回修正": "Level 4 · Drag Back",
	"第 5 关 · 两种选择": "Level 5 · Two Choices",
	"第 6 关 · 长路效率": "Level 6 · Long-Path Efficiency",
	"第 7 关 · 返回岔路": "Level 7 · Return to the Fork",
	"第 8 关 · 绕路取舍": "Level 8 · Worth the Detour",
	"第 9 关 · 水塘补给": "Level 9 · Water Stop",
	"第 10 关 · 综合迁徙": "Level 10 · Full Migration",
	"第 11 关 · 沙丘瞭望": "Level 11 · Dune Watchtower",
	"第 12 关 · 高处来风": "Level 12 · Wind from Above",
	"第 13 关 · 水源与远景": "Level 13 · Water and Vista",
	"第 14 关 · 回望旧路": "Level 14 · Looking Back",
	"第 15 关 · 双向取舍": "Level 15 · Two Detours",
	"第 16 关 · 长路穿沙": "Level 16 · Long Road Through Sand",
	"第 17 关 · 深雾救援": "Level 17 · Deep-Fog Rescue",
	"第 18 关 · 水塘之后": "Level 18 · Beyond the Pond",
	"第 19 关 · 两座营地": "Level 19 · Two Camps",
	"第 20 关 · 明亮尽头": "Level 20 · Bright Horizon",
	"从蓝点数字开始，连接相邻数字凑成 24": "Start at a blue-dot tile and connect adjacent numbers to make 24.",
	"每段新路都要从已经连通的道路边缘出发": "Every new path must begin beside the connected road.",
	"路径可以转弯，但不能穿过岩石": "Paths may turn, but cannot pass through rocks.",
	"选错数字时，拖回上一格即可撤销末段": "Drag back one tile to correct the current chain.",
	"道路边缘可能同时出现多条合法的 24 路径": "Several valid 24 paths can appear along the road frontier.",
	"较长的 24 路径能用同一天开出更多道路": "Longer 24 paths open more road in a single day.",
	"可以从旧道路的任意前沿继续开路": "You may continue from any frontier on the existing road.",
	"偏离主路会增加迁徙日，但也能探索更多区域": "A detour costs a day, but reveals more of the map.",
	"先连接蓝色水塘完成补给，再打开通往绿洲的出口": "Reach the blue pond before opening the oasis exit.",
	"综合使用长路径、转弯、分支与出口判断": "Combine long paths, turns, branches, and exit planning.",
	"绕路点亮瞭望塔，大片薄雾会从高处散开": "Detour to a watchtower to clear a wide area of fog.",
	"比较直达与瞭望绕路，用视野换取更稳的规划": "Compare the direct route with a watchtower detour.",
	"水塘决定出口，瞭望塔决定你能提前看到多远": "The pond unlocks the exit; the tower expands your view.",
	"从旧道路折返瞭望点，再回到更有价值的前沿": "Return along old roads to scout from a watchtower.",
	"伙伴与瞭望塔分居两侧，选择值得付出的迁徙日": "The partner and tower lie apart; choose which detours matter.",
	"连续长路径快速推进，瞭望绕路提供全局判断": "Chain long paths while a tower offers the bigger picture.",
	"用瞭望视野定位伙伴，再从旧前沿展开救援": "Use the tower to locate a partner, then rescue from an old frontier.",
	"先完成补给，再决定是否为远景多走一天": "Restock first, then decide if the vista is worth a day.",
	"在多个旧前沿间切换，兼顾瞭望与掉队伙伴": "Switch between old frontiers to scout and rescue.",
	"综合瞭望、补给、伙伴与长路径完成最终迁徙": "Combine towers, water, partners, and long paths in the finale.",
	"暂停与设置": "Pause & Settings",
	"继续迁徙": "Resume",
	"声音": "Sound",
	"震动": "Vibration",
	"减少动态": "Reduced Motion",
	"语言": "Language",
	"中文": "Chinese",
	"英文": "English",
	"开启": "On",
	"关闭窗口": "Close",
	"关闭": "Off",
	"返回章节地图": "Chapter Map",
	"重置": "Reset",
	"撤回": "Undo",
	"分级提示": "Hint",
	"回到队伍": "Find Party",
	"迁徙路线": "Migration Route",
	"推荐": "Goal",
	"伙伴": "Partners",
	"水塘": "Pond",
	"瞭望": "Tower",
	"从道路边缘开始": "Start from the road frontier",
	"还差": "Need",
	"可以开路": "Path ready",
	"超过": "Over by",
	"向后拖动": "drag backward",
	"迁徙路线已打通": "Migration route complete",
	"动物队伍安全抵达新绿洲": "The animal party reached the new oasis",
	"继续下一关": "Next Level",
	"完成本章": "Finish Chapter",
	"抵达": "Arrival",
	"远行家": "Wayfinder",
	"探索": "Explorer",
	"先锋": "Pioneer",
	"前方暂时无路": "No path ahead",
	"队伍在沙丘中迷路了": "The party is lost in the dunes",
	"迁徙向导会保留已有道路，选择一种方式重新找路": "The guide will preserve your roads. Choose a way forward.",
	"向导可以重整路标，或带队伍从营地重新出发": "The guide can reset the signs or lead the party back to camp.",
	"沿路返回": "Follow the Road Back",
	"请向导重整": "Ask the Guide",
	"返回营地": "Return to Camp",
	"向导确认这条迁徙线无法抵达绿洲，请撤回或请求重整": "The guide found this route cannot reach the oasis. Undo or ask for help.",
	"向导暂时无法确认安全路线，请先撤回一步再观察": "The guide cannot confirm a safe route yet. Undo once and look again.",
	"完整提示：这条路径已确认可以继续抵达绿洲": "Full hint: this path is verified to continue to the oasis.",
	"向导重新整理了路标，这条新路线已经确认能够抵达绿洲": "The guide reset the signs and verified a route to the oasis.",
	"向导无法安全重整当前路线，请撤回上步或重置地图": "The guide cannot safely reshape this route. Undo or restart.",
	"选择一种恢复方式，动物队伍不会丢失": "Choose a recovery option. No progress will be lost.",
	"这是开局死路，请重整边界或重置地图": "This opening has no move. Reshuffle or reset.",
	"撤回上步": "Undo",
	"重整边界": "Reshuffle",
	"重置地图": "Reset",
	"出口": "Exit",
	"补给后开启": "Opens after pond",
	"绿洲家园": "Oasis Home",
	"迁入居民": "Residents",
	"家园装饰": "Home Decorations",
	"本章没有额外救援目标": "No rescue residents in this chapter.",
	"等待救援": "Awaiting rescue",
	"使用中": "Selected",
	"点击更换": "Tap to select",
	"尚未解锁": "Locked",
	"自然绿洲": "Natural Oasis",
	"迁徙风铃": "Journey Chimes",
	"彩色花圃": "Flower Garden",
	"伙伴凉棚": "Companion Shade",
	"星光灯串": "Star Lanterns",
	"庆典彩旗": "Festival Flags",
	"耳廓狐": "Fennec",
	"狐獴": "Meerkat",
	"岩羊": "Ibex",
	"幼象": "Elephant Calf",
	"长颈鹿": "Giraffe",
	"水源重新涌动": "Water is flowing again",
	"草木正在生长": "Greenery is returning",
	"伙伴们的新家": "A new home for the animals",
	"完全复苏的绿洲": "A fully restored oasis",
	"等待复苏的绿洲": "An oasis awaiting renewal",
	"已完成": "Completed",
	"完成": " Complete",
	"绿洲生机": "Oasis Vitality",
	"获救居民": "Rescued Residents",
	"成果会解锁新的家园装饰": "Achievements unlock new home decorations",
	"生机解锁": "vitality to unlock",
	"点击已解锁的关卡继续迁徙": "Tap an unlocked level to continue",
	"先完成前一关，迁徙路线就会继续展开": "Complete the previous level to extend the route.",
	"完成本章最后一关后，明亮的迁徙路线会继续展开": "Finish this chapter to reveal the next route.",
	"水": "Pond",
	"终": "Goal",
	"锁": "Locked",
	"键盘：1–9/0 当前章节　F3 死局测试　R 重置　U 撤回　G 看绿洲　A 主路　B 支路": "Keys: 1–9/0 level · R reset · U undo · G oasis · A route · B branch",
	"开局没有可用路径，已自动暂停并提供恢复操作": "No opening move. Recovery options are ready.",
	"先沿蓝色水滴指引找到水塘，补给后出口才会开启": "Follow the blue drop to the pond; the exit opens after restocking.",
	"从起点边缘连接数字，凑成 24": "Connect numbers from the starting frontier to make 24.",
	"当前没有可用的 24 路径，请选择恢复操作": "No valid 24 path remains. Choose a recovery option.",
	"罗盘提示：从高亮的道路前沿开始观察": "Compass: inspect the highlighted road frontier.",
	"方向提示：前两个数字已经标出，继续凑成 24": "Direction: the first two tiles are marked; continue to 24.",
	"完整提示：已标出一条可用的 24 路径": "Full hint: a valid 24 path is highlighted.",
	"当前没有可以撤回的开路步骤": "There is no path-building step to undo.",
	"已撤回上一次开路，还可撤回": "Undid the last path. Undo steps remaining:",
	"已撤回上一次开路，可以重新选择方向": "Undid the last path. Choose a new direction.",
	"道路边缘已重整，罗盘标出了新的可行动前沿": "The frontier was reshuffled; the compass marks a new move.",
	"边界空间不足，无法重整，请重置地图": "Not enough frontier space to reshuffle. Reset the map.",
	"当前没有下一段预设路径": "No next authored route segment is available.",
	"当前支路尚未与道路前沿连通": "The branch has not reached the road frontier yet.",
	"动物队伍已经抵达新的绿洲！": "The animal party has reached the new oasis!",
	"先把绿色道路连接到蓝色水塘，完成途中补给": "Connect the green road to the blue pond to restock.",
	"目标绿洲位于唯一出口之外": "The target oasis lies beyond the only exit.",
	"出口尚未开启：请先连接蓝色水塘完成补给": "The exit is closed. Reach the pond first.",
	"路径未达到 24，已取消": "The path did not total 24 and was cancelled.",
	"开发错误：合法路径未能应用": "Internal error: the valid path could not be applied.",
	"出口已经打通，动物队伍正在前往绿洲": "The exit is open; the party is heading to the oasis.",
	"道路前沿没有可用路径，已打开恢复面板": "No move remains on the frontier. Recovery options are open.",
	"找到了迷路的耳廓狐！它已经加入迁徙队伍": "The lost fennec has joined the migration party!",
	"水塘补给完成！通往目标绿洲的出口已经开启": "Restocking complete! The oasis exit is now open.",
	"瞭望点已点亮！高处视野驱散了周围大片薄雾": "Watchtower lit! Its view cleared a wide area of fog.",
	"开路成功，继续从绿色道路边缘出发": "Path opened. Continue from the green road frontier.",
	"按住带蓝点的数字开始连线": "Hold the blue-dot number to begin.",
	"继续拖过相邻数字，让总和达到 24": "Drag across adjacent numbers until the total reaches 24.",
	"草路已经长出，从新的道路边缘继续": "The grass road has grown. Continue from its new frontier.",
	"小地图已将镜头带到目标绿洲": "The minimap centered the target oasis.",
	"小地图已将镜头带到途中补给水塘": "The minimap centered the restocking pond.",
	"迁徙完成：动物队伍已经安全抵达新绿洲": "Migration complete: the animal party reached the new oasis.",
	"新的绿洲已经恢复": "The new oasis has been restored.",
	"新绿洲已经恢复": "The new oasis has been restored.",
	"动物队伍获得了新的家园": "The animal party has a new home.",
	"所有现有章节已经完成": "All current chapters are complete.",
	"进入下一章": "Next Chapter",
	"家园装饰已更换为": "Home decoration changed to",
	"继续收集成果，达到": "Keep earning achievements. Unlocks at",
	"点生机即可解锁": "vitality.",
	"迁徙章节": "Migration Chapter",
	"达成推荐": "Goal achieved",
	"迁徙日": "migration days",
	"内部验证": "Internal Test",
	"内部测试 · 无路恢复": "Internal Test · Dead-End Recovery",
	"该地图仅用于验证自动死局检测和恢复操作": "This map verifies automatic dead-end detection and recovery.",
}


static func set_language(value: String) -> void:
	language = value if value in ["zh", "en"] else "zh"


static func text(source: String) -> String:
	if language != "en" or source.is_empty():
		return source
	var result := source
	var keys := EN.keys()
	keys.sort_custom(func(a, b) -> bool: return str(a).length() > str(b).length())
	for key_variant in keys:
		var key := str(key_variant)
		if result.contains(key):
			result = result.replace(key, str(EN[key]))
	if result.begins_with("第 ") and result.ends_with(" 天"):
		result = "Day %s" % result.trim_prefix("第 ").trim_suffix(" 天")
	if result.begins_with("第 ") and result.ends_with(" 步"):
		result = "Step %s" % result.trim_prefix("第 ").trim_suffix(" 步")
	result = result.replace(" 天", " days")
	result = result.replace("用了 ", "Used ")
	result = result.replace(" 个迁徙日", " migration days")
	result = result.replace(" 个migration days", " migration days")
	result = result.replace(" 步", " steps")
	return result
